### ISSUE TITLE
VS Code Gradle Extension Duplicates and Repeats Tasks

### ISSUE THREAD

**Issue by Yahya-Allam** [badsyntax/vscode-gradle#1194] opened 2022-03-08 22:06 UTC
Extension Name: vscode-gradle
Extension Version: v3.11.0
OS Version: Windows 10 Enterprise 64-bit (10.0, Build 19042)
VSCode version: 1.65.1 (system setup)

**Describe the bug**
This bug started with version 3.10.0 it was not happening in previous versions.
When the extension starts to search for tasks it duplicates the tasks extensively.

**To Reproduce**
1. Open a project that has nested /sub-projects like Liferay projects.
2. the Gradle extension will start scanning the project automatically for tasks, 

**Expected behavior**
For nested projects, Gradle extension will duplicate their tasks, in the output snaps it has produced **46468** tasks!

**Screenshots**
![image](https://user-images.githubusercontent.com/76212827/157327618-d05c7aeb-50ec-4726-826c-e0962576a5f3.png)
![image](https://user-images.githubusercontent.com/76212827/157333398-eaf161de-dde2-41aa-9201-e667da21f907.png)

**Output from "Gradle for Java"**

```
[debug] [gradle-server] Starting server
[debug] [gradle-server] Gradle Server cmd: c:\Users\user.name\.vscode\extensions\vscjava.vscode-gradle-3.11.0\lib\gradle-server.bat 51621
[info] [gradle-server] Server started, listening on 51621
[info] Gradle client connected to server
[info] Java Home: C:\Program Files\Java\jdk1.8.0_301
[info] JVM Args: -XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\user.name\.gradle
[info] Gradle Version: 6.6.1
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 1m 49s
[debug] Refreshing tasks
[info] Found 46468 tasks
```

**Additional context**
from Settings.json:
```
{
 "java.jdt.ls.java.home": "C:\\Program Files\\Amazon Corretto\\jdk11.0.12_7",
 "java.configuration.runtimes": [  
        {
            "name": "JavaSE-1.8",
            "path": "C:\\Program Files\\Java\\jdk1.8.0_301",
            "sources": "C:\\Program Files\\Java\\jdk1.8.0_301\\src.zip",
            "javadoc": "https://docs.oracle.com/javase/8/docs/api",
            "default": true
        },

        {
            "name": "JavaSE-11",
            "path": "C:\\Program Files\\Amazon Corretto\\jdk11.0.12_7",
            "sources": "C:\\Program Files\\Amazon Corretto\\jdk11.0.12_7\\lib\\src.zip"
        }

    ],
     "gradleLang.trace.server": "verbose",
    "gradle.debug": true,
    "java.import.gradle.java.home": "C:\\Program Files\\Java\\jdk1.8.0_301",
    "gradle.nestedProjects": true,
 }
```

**Comment by CsCherrYY** [comment] 2022-03-09 01:39
Thanks for reporting. Could you

- try to set "gradle.nestedProjects" to `false` to see if this issue still exists
- provide a sample project to help me reproduce this issue

**Comment by Yahya-Allam** [comment] 2022-03-09 23:20
Thank you @CsCherrYY  
Actually the same ... and the number has not been changed.
[info] Found 46468 tasks

**Comment by Yahya-Allam** [comment] 2022-03-16 20:12
Another issue [I will mention its number here when I open it] appeared with the test configuration inside the Gradle file so I have downgraded to version 3.9.0 and this issue and the issue related to the test configuration have disappeared.

**Comment by CsCherrYY** [comment] 2022-04-02 02:20
hi @Yahya-Allam , for this issue, could you provide a sample project to help me reproduce this, so I can fix it?

**Comment by leolcao** [comment] 2022-05-02 07:29
Hi @CsCherrYY  I reproduced this bug in my local, I prepared the github repo as reference: https://github.com/llc-public/vscode-gradle-sample

I find the root trigger is about the way to include subprojects in the settings.gradle.

For example, I put `apps/java-hello` and `java-hello2` in my git repo, the gradle extension version is v3.12.0, I can see 2 duplicated tasks for the apps/java-hello, but only one for java-hello2.

![image](https://user-images.githubusercontent.com/539695/166199393-47dbf3bd-c354-414d-997b-7ea870989264.png)

This behavior also appear in the nested projects. check the `projects/apps/java-hello3` and `projects/java-hello4` which is corrent.

![image](https://user-images.githubusercontent.com/539695/166199567-d7381611-ac1c-4c94-8eb4-a1bd895d0480.png)

BTW, for the 'apps/' folder, this extension also show duplicated tasks, like below:
![image](https://user-images.githubusercontent.com/539695/166203590-1dd5426a-7e20-4464-b9f1-45d151ddc126.png)

**Comment by CsCherrYY** [comment] 2022-05-05 03:16
@leolcao I can reproduce this! Thanks for the sample project. I'll take a look and prepare a fix.

**Comment by leolcao** [comment] 2022-05-05 10:03
Feel happy for the recognization with my sample repo. this extension is a great work to let me stay on vscode. btw, this bug aslo appear in the nested projects which be included in my sample repo too.

**Comment by CsCherrYY** [comment] 2022-05-17 02:15
@leolcao the fix has been proposed in #1224, with this PR, your sample project seems to work well.

![image](https://user-images.githubusercontent.com/45906942/168714581-2ba8f5eb-f5f4-4ab5-a9e3-cbad197db997.png)

**Comment by leolcao** [comment] 2022-05-17 03:19
Wow, big thanks for the quick fixing, and the codes look clear to hit the root cause. Looking forward the new version of this extension~ For now, I still can work with this bug, it doesn't affect the functionality after all.

**Closed as completed** 2022-05-17 05:36 UTC
Labels: bug

**Comment by CsCherrYY** [comment] 2022-05-17 05:51
@leolcao Thanks for the help. you can now switch to the newest pre-release version (`3.12.2022051705`) to see if it works.

**Comment by Yahya-Allam** [comment] 2022-05-17 12:10
@leolcao thank you for helping in reproducing the issue.

**Comment by Yahya-Allam** [comment] 2022-05-17 12:13
@CsCherrYY I am very sorry for being late in helping you. Please accept my apology.
Many thanks to you for being helpful. Thank you for your time and consideration. I will continue to be a big fan of vs code.

**Comment by CsCherrYY** [comment] 2022-05-17 12:58
@Yahya-Allam Thanks for reporting! Hope this fix helps. If you find any other issue or any feature request, please feel free to reach out😀

**Comment by leolcao** [comment] 2022-05-18 00:28
@CsCherrYY I tried the latest version `3.12.2022051800` actually, the bug is fixed in my git repos.

**Comment by softwareCobbler** [comment] 2023-12-30 14:56
I see this on 3.13.5, with the following project layout:

```
$home/project/settings.gradle.kts
$home/project/project/build.gradle.kts
```
Where the project root folder's name is the same as a sub-project's folder name. The root settings.gradle.kts is one line:
```
include("project")
```
