### ISSUE TITLE
Extension publisher id update seems to be causing issues

### ISSUE THREAD

**Issue by badsyntax** [badsyntax/vscode-gradle#1007] opened 2021-09-21 18:43 UTC
Hey. I noticed the publisher id was updated but i'm seeing a few issues related to that:

This is causing issues in dependant extensions when depending on "vscjava.vscode-gradle" because it seems that although the publisher id is updated, some other internal id isn't:

<img width="549" alt="Screenshot 2021-09-21 at 19 39 56" src="https://user-images.githubusercontent.com/102141/134228974-6d58a1b5-5306-4808-9430-45bed8e72184.png">

(If I click "Install and reload" it goes into a loop and the extension is never installed.)

See various issues trying to install the extension: 

https://user-images.githubusercontent.com/102141/134228440-667f1767-3ab2-44b3-b317-58f5c0f97775.mov

When I am able to install it, look at the running extension process id when viewing "Developer: Show Running Extensions", it's still the old publisher id:

<img width="476" alt="Screenshot 2021-09-21 at 19 41 12" src="https://user-images.githubusercontent.com/102141/134228796-71f12b26-16c0-4150-81e5-d2c86d01a195.png">

**Comment by badsyntax** [comment] 2021-09-21 18:49
cc @nickzhums @akaroml

**Comment by Eskibear** [comment] 2021-09-22 01:41
We should publish a new version after updating its publisher, and we are about to do it now. Let me take a look if that's related.

However I cannot simply reproduce the error message on my side. 
![image](https://user-images.githubusercontent.com/2351748/134269693-bf7eb99e-a44d-4a08-b737-251f7d466991.png)


[2021-09-22 09:33:47.284] [exthost] [info] ExtensionService#_doActivateExtension richardwillis.vscode-spotless-gradle {"startup":false,"extensionId":{"value":"richardwillis.vscode-spotless-gradle","_lower":"richardwillis.vscode-spotless-gradle"},"activationEvent":"workspaceContains:gradlew"}

**Comment by Eskibear** [comment] 2021-09-22 01:47
Above is the case when I have already installed Gradle Tasks extension. 

I can reproduce the issue that I cannot install Gradle Tasks extension **from scratch**. It should be fixed when we release a new version. I'll update if it works.

**Comment by badsyntax** [comment] 2021-09-22 06:02
@Eskibear yes I experienced the same. I only became aware of this issue when installing the extension from scratch (as part of integration tests for `vscode-spotless-gradle`: https://github.com/badsyntax/vscode-spotless-gradle/pull/242)

**Comment by badsyntax** [comment] 2021-09-22 07:14
I can confirm there are no problems with `3.6.2`. My integration tests for `vscode-spotless-gradle` are now working correctly using `vscode-gradle@3.6.2`. 

(But I have also noticed there is no README anymore at https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle)

**Comment by CsCherrYY** [comment] 2021-09-22 07:23
> I can confirm there are no problems with 3.6.2. My integration tests for vscode-spotless-gradle are now working correctly using vscode-gradle@3.6.2.

Thank you for the information!

> (But I have also noticed there is no README anymore at https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle)

We observed this issue as well. It might be due to the `repository` in package.json of `3.6.2` is still pointing to your original repo url. See https://github.com/microsoft/vscode-gradle/blob/1fbc1a5c9646c9771dd3e081cbf2a2b5dce31beb/extension/package.json#L19

But in `3.7.0`, it will become https://github.com/microsoft/vscode-gradle. As @nickzhums previously mentioned, we will release `3.7.0` as the version including changes from our side, let's see if we can fix this in the new version.

**Comment by badsyntax** [comment] 2021-09-22 07:24
Makes sense, and sounds good, thanks!

**Comment by CsCherrYY** [comment] 2021-09-22 07:51
@badsyntax We have released `3.7.0`, unfortunately the `Overview` of the extension website is still unavailable. We're contacting our marketplace team for help. I'll comment here if there is any update.

For those users in `3.6.2`, they can automatically update to `3.7.0`.

**Comment by CsCherrYY** [comment] 2021-09-23 05:59
@badsyntax We have released `3.7.1` to fix the bug missing `Details` and `Changelog` tabs. Could you please have a try to see if this issue still exists?

**Comment by badsyntax** [comment] 2021-09-23 06:10
@CsCherrYY Looks good to me. The README is now [displaying correctly](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) and I'm able to uninstall and install the extension without any problems, and dependant extensions (vscode-spotless-gradle) still work fine. Feel free to close!

**Comment by CsCherrYY** [comment] 2021-09-23 06:12
@badsyntax Thanks again for the help and information!

**Closed as completed by CsCherrYY** 2021-09-23 06:12 UTC
Labels: bug
